// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Assigner is an autogenerated mock type for the Assigner type
type Assigner struct {
	mock.Mock
}

// Assign provides a mock function with given fields: destination, source
func (_m *Assigner) Assign(destination *int, source int) {
	_m.Called(destination, source)
}

// Count provides a mock function with given fields:
func (_m *Assigner) Count() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
