// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Comparer is an autogenerated mock type for the Comparer type
type Comparer struct {
	mock.Mock
}

// Compare provides a mock function with given fields: left, right
func (_m *Comparer) Compare(left int, right int) bool {
	ret := _m.Called(left, right)

	var r0 bool
	if rf, ok := ret.Get(0).(func(int, int) bool); ok {
		r0 = rf(left, right)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}

// Count provides a mock function with given fields:
func (_m *Comparer) Count() int {
	ret := _m.Called()

	var r0 int
	if rf, ok := ret.Get(0).(func() int); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(int)
	}

	return r0
}
